--- !ruby/object:Alias
cfile: /Users/tvuong/.alias.yml
dellist: !ruby/object:Hash {}
oldlist: !ruby/object:Hash {}
valias: 
version: 174
valias: 
  _ALIAS_VERSION:
  - "'173'"
  - ".alias-common"
  dgrep:
  - "'devtool grep'"
  - ""
  edemt:
  - "'devtool ed -d ~/emtools'"
  - ".alias-common"
  edetf:
  - "'devtool ed -d ~/etfw2'"
  - ".alias-common"
  edprof:
  - "'emtool ed -d ~/myprofile'"
  - ".alias-common"
  edx:
  - "'shtool edx'"
  - ".alias-common"
  emed:
  - "'emtool ed'"
  - ".alias-common"
  gconnect:
  - "'cd2 /etrade/home/tvuong/connect/webapp'"
  - ".alias-common"
  h:
  - "'history 20'"
  - ".alias-common"
  perld:
  - "'perl -d -e 42'"
  - ".alias-common"
  qu:
  - "'qu.rb restore'"
  - ".alias-common"
  ssh:
  - "'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'"
  - ".alias-common"
