--- !ruby/object:Alias
cfile: /Users/tvuong/.alias.yml
dellist: !ruby/object:Hash {}
oldlist: !ruby/object:Hash {}
valias: 
version: 174
valias: 
  _ALIAS_VERSION:
  - "'173'"
  - ".alias-common"
  citrix:
  - "'open https://citrix.etrade.com/vpn/index.html'"
  - ".alias-common"
  css2:
  - "'emssh run -th tvuong@poc1w80m7.etrade.com emtools/bin/screens resume'"
  - ".alias-common"
  cwa:
  - "'open -a '\''Google Chrome'\'' https://cwa.corp.etradegrp.com'"
  - ".alias-common"
  dgrep:
  - "'devtool grep'"
  - ""
  edemt:
  - "'devtool ed -d ~/emtools'"
  - ".alias-common"
  edetf:
  - "'devtool ed -d ~/etfw2'"
  - ".alias-common"
  edmt:
  - "'devtool ed -d ~/myprofile'"
  - ".alias-common"
  edprof:
  - "'emtool ed -d ~/myprofile'"
  - ".alias-common"
  edrail:
  - "'railtool ed'"
  - ".alias-common"
  edx:
  - "'shtool edx'"
  - ".alias-common"
  emdb:
  - "'open http://lxp6d199m0:3002/emdb/'"
  - ".alias-common"
  emed:
  - "'emtool ed'"
  - ".alias-common"
  ervm:
  - "'source ~/.rvm/scripts/rvm'"
  - ""
  essh:
  - "'emssh run -h'"
  - ".alias-common"
  fs:
  - "'fsh -l tvuong'"
  - ".alias-common"
  gconnect:
  - "'cd2 /etrade/home/tvuong/connect/webapp'"
  - ".alias-common"
  goem:
  - "'cd2 /home/tvuong/em/src'"
  - ".alias-common"
  goem2:
  - "'cd2 /etrade/home/tvuong/em2'"
  - ".alias-common"
  goetfw:
  - "'cd2 /etrade/home/tvuong/etfw/src/tools'"
  - ".alias-common"
  goyum2:
  - "'cd2 /etrade/tools/yum-repo2/rhas3/i386/corp/packages'"
  - ".alias-common"
  goyum5:
  - "'cd2 /etrade/tools/yum-repo/rhas5/i386/corp/packages'"
  - ".alias-common"
  goyum6:
  - "'cd2 /etrade/tools/yum-repo2/rhas4/x86_64/corp/packages'"
  - ".alias-common"
  gozip:
  - "'cd2 /etrade/tools/yum-repo/zip/i386'"
  - ".alias-common"
  grail:
  - "'cd2 /etrade/home/tvuong/etool/staf-rails'"
  - ".alias-common"
  graild:
  - "'cd2 /etrade/home/tvuong/selaf/webapp'"
  - ".alias-common"
  h:
  - "'history 20'"
  - ".alias-common"
  ib:
  - "'cd $ET_INSTANCE_ROOT/bin'"
  - ".alias-common"
  ic:
  - "'cd $ET_INSTANCE_ROOT/config'"
  - ".alias-common"
  ie:
  - "'cd $ET_INSTANCE_ROOT/etc'"
  - ".alias-common"
  il:
  - "'cd $ET_INSTANCE_ROOT/logs'"
  - ".alias-common"
  ilc:
  - "'$ANTDEPO_BASE/depots/$ET_APPLICATION/lib/ant/modules/$ET_SERVER/commands'"
  - ".alias-common"
  l.:
  - "'ls -d .* --color=tty'"
  - ".alias-common"
  la:
  - "'ls -A'"
  - ".alias-common"
  ll:
  - "'ls -l --color=tty'"
  - ".alias-common"
  locate:
  - "'mdfind -name'"
  - ".alias-common"
  mpshell:
  - "'~/kamplayer/bin/katool mpshell'"
  - ".alias-common"
  penv:
  - "'/usr/bin/env | /bin/grep ^ET_'"
  - ".alias-common"
  perld:
  - "'perl -d -e 42'"
  - ".alias-common"
  qu:
  - "'qu.rb restore'"
  - ".alias-common"
  ragrep:
  - "'railtool grep'"
  - ".alias-common"
  rdesk:
  - "'vnc rdesktop -u tvuong'"
  - ".alias-common"
  remote:
  - "'open https://remote.etrade.com'"
  - ".alias-common"
  rm:
  - "'_rm'"
  - ""
  rr:
  - "'emssh run'"
  - ".alias-common"
  rsetup:
  - "'emssh run -th tvuong@lxp6d199m0 bin/sshsetup setup'"
  - ".alias-common"
  rsync:
  - "'rsync --rsh=ssh'"
  - ".alias-common"
  rvm-restart:
  - "'rvm_reload_flag=1 source '\''/Users/tvuong/.rvm/scripts/rvm'\'''"
  - ""
  s:
  - "'emssh connect'"
  - ".alias-common"
  s2:
  - "'screens resume'"
  - ".alias-common"
  s3:
  - "'screens resume'"
  - ".alias-common"
  s4:
  - "'stmux'"
  - ".alias-common"
  s41:
  - "'emssh run -th tvuong@poc1w80m7.etrade.com emtools/bin/emtmux resume'"
  - ".alias-common"
  sclearcase:
  - "'ssh -X dev2m12'"
  - ".alias-common"
  scolinux:
  - "'ssh -X -l thien -p 2022 mb45-0095'"
  - ".alias-common"
  seled:
  - "'selaf ed'"
  - ".alias-common"
  sgrep:
  - "'selaf grep'"
  - ".alias-common"
  sl:
  - "'SSH_PORT=2022 emssh connect tvuong@localhost'"
  - ".alias-common"
  slinux:
  - "'ssh -X -ltvuong -p2222 localhost'"
  - ".alias-common"
  slinux2:
  - "'ssh -X lxp6d199m0'"
  - ".alias-common"
  ssh:
  - "'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'"
  - ".alias-common"
  tgrep:
  - "'etoolset grep'"
  - ".alias-common"
  trace:
  - "'etlogger -o trace'"
  - ".alias-common"
  unrar:
  - "'/Applications/jDownloader.app/Contents/Resources/Java/tools/mac/unrar2/unrar'"
  - ".alias-common"
  vbm:
  - "'VBoxManage'"
  - ".alias-common"
  vssh:
  - "'vagrant ssh'"
  - ".alias-common"
  vzyum3m:
  - "'sudo vzyum  -c http://lxp6d199m0/yum-repo/rhas5/i386/corp/etem.repo'"
  - ".alias-common"
  yumbeta:
  - "'sudo yum -c http://yum.etrade.com/proxy/p6.rhas3.x86/dev-main-beta/yum.conf'"
  - ".alias-common"
  yumem:
  - "'sudo yum -c http://lxp6d199m0/yum-repo/rhas5/i386/corp/etem.repo'"
  - ".alias-common"
  yumem3:
  - "'etcmd -s yum -c http://lxp6d199m0/yum-repo/rhas3/i386/corp/etem.repo'"
  - ".alias-common"
  yumem5:
  - "'sudo yum -c http://lxp6d199m0/yum-repo/rhas5/i386/corp/etem.repo'"
  - ".alias-common"
  yumgold:
  - "'sudo yum -c http://yum.etrade.com/proxy/p6.rhas3.x86/dev-main-gold/yum.conf'"
  - ".alias-common"
  yumtest:
  - "'sudo yum -c http://yum.etrade.com/proxy/p6.rhas3.x86/dev-main-test/yum.conf'"
  - ".alias-common"
