#!/bin/env bash
. ${0%/*}/app.env
############################################################################
# File:        /home/tvuong/bin/mount_usb
# Author:      tvuong
# Created:     2024-02-17 16:39:15 -0800
# Copyright (c) Thien H Vuong - 2024.
# Description:
# $Id$
############################################################################

oper=$1; shift
case $oper in
  cmd|powershell|pwsh)
    session=$oper
    shell=$session.exe
    tmux new-session -d -s $session $shell
    tmux set -t $session default-command $shell
    exec tmux attach -t $session
    ;;

  *)
    F_usageOper $oper
    emman.rb gen-use $0
    ;;
esac
exit 0

__END__

=head1 NAME
tmuxfor - Helper script to support tmux operations for windows shells

=head1 SYNOPSIS
General form: tmuxfor operation [options] [parameters]

  * tmuxfor cmd:powershell:pwsh

=head1 DESCRIPTION

This contains various utilities to support use of WSL interoperation

=head1 OPERATIONS

